In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
np.random.seed(42)
#set random seed for exact reproducibility 

n = 1000 
#n = number of cross-sectional household observations

In [9]:
data = {'household_id' : range(1, n+1), 
       'income':np.random.lognormal(mean=10.5, sigma = 0.6, size = n), 
       # annual income
       'wealth':np.random.lognormal(mean = 11.5, sigma = 1.0, size = n),
       # total net wealth 
       'debt':np.random.exponential(scale=15000, size=n),           
       # Total household debt
       'age':np.random.randint(25, 70, size=n),                     
       # Age of household head
       'stock_market_participant':np.random.choice([0, 1], size=n, p=[0.6, 0.4]), 
       # 1 if invested in equities
       'liquidity_constrained':np.random.choice([0, 1], size=n, p=[0.7, 0.3])     
       # 1 if lacking emergency liquidity 
}

In [10]:
df = pd.DataFrame(data)

In [12]:
print(df)
# display the data

     household_id         income         wealth          debt  age  \
0               1   48924.251431  400054.247877   7841.107096   35
1               2   33424.398935  248856.992441   1024.340709   52
2               3   53562.963185  104781.275909   6434.549959   56
3               4   90564.529961   51692.253945   1764.838573   29
4               5   31555.651338  198436.278729  24772.285651   62
..            ...            ...            ...           ...  ...
995           996   30679.189101  287837.176054   6292.969417   62
996           997  106789.182840   96132.116776  29999.357731   66
997           998   53343.409550   40868.928084   2524.953995   62
998           999   25778.410187   83862.433261   1295.412958   47
999          1000   51202.808796   46868.325097   9940.375253   49

     stock_market_participant  liquidity_constrained
0                           1                      0
1                           1                      0
2                           1                      0
3                           0                      0
4                           0                      1
..                        ...                    ...
995                         1                      1
996                         0                      0
997                         0                      1
998                         0                      0
999                         1                      0

[1000 rows x 7 columns]

In [14]:
df.head()
# display the first 5 rows

,household_id,income,wealth,debt,age,stock_market_participant,liquidity_constrained
0,1,48924.251431,400054.247877,7841.107096,35,1,0
1,2,33424.398935,248856.992441,1024.340709,52,1,0
2,3,53562.963185,104781.275909,6434.549959,56,1,0
3,4,90564.529961,51692.253945,1764.838573,29,0,0
4,5,31555.651338,198436.278729,24772.285651,62,0,1

In [15]:
print(df.shape)
# display dataframe dimensions (rows, columns)

(1000, 7)

In [13]:
df.loc[df['income'] < 20000, 'debt'] = np.nan

In [16]:
df.info()
# check column data types and non-null counts

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   household_id              1000 non-null   int64
 1   income                    1000 non-null   float64
 2   wealth                    1000 non-null   float64
 3   debt                      852 non-null    float64
 4   age                       1000 non-null   int64
 5   stock_market_participant  1000 non-null   int64
 6   liquidity_constrained     1000 non-null   int64
dtypes: float64(3), int64(4)
memory usage: 54.8 KB

In [18]:
df.describe()

# generate descriptive summary statistics

,household_id,income,wealth,debt,age,stock_market_participant,liquidity_constrained
count,1000.000000,1000.000000,1.000000e+03,852.000000,1000.000000,1000.00000,1000.000000
mean,500.500000,43842.690240,1.728404e+05,15096.826693,47.200000,0.38200,0.295000
std,288.819436,29631.713320,2.126575e+05,14961.204307,12.874617,0.48612,0.456271
min,1.000000,5193.897179,5.216653e+03,0.174522,25.000000,0.00000,0.000000
25%,250.750000,24623.249457,5.383929e+04,4317.298712,37.000000,0.00000,0.000000
50%,500.500000,36870.995082,1.051432e+05,10621.856468,47.000000,0.00000,0.000000
75%,750.250000,53571.171675,2.046148e+05,20937.577579,58.000000,1.00000,1.000000
max,1000.000000,366457.889401,2.405113e+06,102086.268298,69.000000,1.00000,1.000000

In [19]:
print(df.isna().sum())

# total missing values per variable

household_id                  0
income                        0
wealth                        0
debt                        148
age                           0
stock_market_participant      0
liquidity_constrained         0
dtype: int64

In [20]:
print(df['stock_market_participant'].value_counts(normalize=True))

stock_market_participant
0    0.618
1    0.382
Name: proportion, dtype: float64